services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: users_db_kv
      POSTGRES_USER: wendeladminn
      POSTGRES_PASSWORD: "@wendelAdmin2003"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wendeladminn -d users_db_kv"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: KonvertaCRM
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://wendeladminn:@wendelAdmin2003@postgres:5432/users_db_kv
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=@wendelAdmin2003
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crm_network
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  crm_network:
    driver: bridge
